// <auto-generated />
using System;
using LibraryManagementDALLibrary.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagementDALLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260514180545_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementDALLibrary.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Authorname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("authorname");

                    b.Property<int>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("edition");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Isbn")
                        .HasName("books_pkey");

                    b.HasIndex("Categoryid");

                    b.HasIndex(new[] { "Authorname" }, "idx_books_author");

                    b.HasIndex(new[] { "Title" }, "idx_books_title");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Bookcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("bookcategories_pkey");

                    b.HasIndex(new[] { "Name" }, "bookcategories_name_key")
                        .IsUnique();

                    b.ToTable("bookcategories", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Bookcopy", b =>
                {
                    b.Property<string>("Barcodeno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcodeno");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Available'::character varying");

                    b.HasKey("Barcodeno")
                        .HasName("bookcopies_pkey");

                    b.HasIndex("Isbn");

                    b.HasIndex(new[] { "Status" }, "idx_bookcopies_status");

                    b.ToTable("bookcopies", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcodeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcodeno");

                    b.Property<DateOnly>("Borrowdate")
                        .HasColumnType("date")
                        .HasColumnName("borrowdate");

                    b.Property<string>("Borrowstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("borrowstatus")
                        .HasDefaultValueSql("'Borrowed'::character varying");

                    b.Property<DateOnly>("Duedate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<int>("Memberid")
                        .HasColumnType("integer")
                        .HasColumnName("memberid");

                    b.Property<DateOnly?>("Returndate")
                        .HasColumnType("date")
                        .HasColumnName("returndate");

                    b.HasKey("Id")
                        .HasName("borrowings_pkey");

                    b.HasIndex("Barcodeno");

                    b.HasIndex(new[] { "Memberid" }, "idx_borrowings_member");

                    b.ToTable("borrowings", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Borrowingid")
                        .HasColumnType("integer")
                        .HasColumnName("borrowingid");

                    b.Property<decimal>("Fineamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fineamount");

                    b.Property<string>("Finetype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("finetype");

                    b.Property<bool>("Ispaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ispaid");

                    b.HasKey("Id")
                        .HasName("fines_pkey");

                    b.HasIndex(new[] { "Borrowingid" }, "idx_fines_borrowing");

                    b.ToTable("fines", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Finepayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amountpaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amountpaid");

                    b.Property<int>("Fineid")
                        .HasColumnType("integer")
                        .HasColumnName("fineid");

                    b.Property<DateTime>("Paymentdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paymentdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("finepayments_pkey");

                    b.HasIndex("Fineid");

                    b.ToTable("finepayments", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accountstatus")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("Membershiptypeid")
                        .HasColumnType("integer")
                        .HasColumnName("membershiptypeid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("members_pkey");

                    b.HasIndex("Membershiptypeid");

                    b.HasIndex(new[] { "Email" }, "idx_members_email");

                    b.HasIndex(new[] { "Phone" }, "idx_members_phone");

                    b.HasIndex(new[] { "Email" }, "members_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "members_phone_key")
                        .IsUnique();

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Membershiptype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Maximumborrowdays")
                        .HasColumnType("integer")
                        .HasColumnName("maximumborrowdays");

                    b.Property<int>("Maximumborrowings")
                        .HasColumnType("integer")
                        .HasColumnName("maximumborrowings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("membershiptypes_pkey");

                    b.HasIndex(new[] { "Name" }, "membershiptypes_name_key")
                        .IsUnique();

                    b.ToTable("membershiptypes", (string)null);
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Book", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Bookcategory", "Category")
                        .WithMany("Books")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_books_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Bookcopy", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Book", "IsbnNavigation")
                        .WithMany("Bookcopies")
                        .HasForeignKey("Isbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookcopies_book");

                    b.Navigation("IsbnNavigation");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Borrowing", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Bookcopy", "BarcodenoNavigation")
                        .WithMany("Borrowings")
                        .HasForeignKey("Barcodeno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_borrowings_bookcopy");

                    b.HasOne("LibraryManagementDALLibrary.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_borrowings_member");

                    b.Navigation("BarcodenoNavigation");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Fine", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Borrowing", "Borrowing")
                        .WithMany("Fines")
                        .HasForeignKey("Borrowingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fines_borrowing");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Finepayment", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Fine", "Fine")
                        .WithMany("Finepayments")
                        .HasForeignKey("Fineid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finepayments_fine");

                    b.Navigation("Fine");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Member", b =>
                {
                    b.HasOne("LibraryManagementDALLibrary.Membershiptype", "Membershiptype")
                        .WithMany("Members")
                        .HasForeignKey("Membershiptypeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_members_membershiptype");

                    b.Navigation("Membershiptype");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Book", b =>
                {
                    b.Navigation("Bookcopies");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Bookcategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Bookcopy", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Borrowing", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Fine", b =>
                {
                    b.Navigation("Finepayments");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Member", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementDALLibrary.Membershiptype", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
